# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import finance_pb2 as finance__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in finance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FinanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTransaction = channel.unary_unary(
                '/FinanceService/AddTransaction',
                request_serializer=finance__pb2.TransactionRequest.SerializeToString,
                response_deserializer=finance__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.GetSummary = channel.unary_unary(
                '/FinanceService/GetSummary',
                request_serializer=finance__pb2.SummaryRequest.SerializeToString,
                response_deserializer=finance__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_stream(
                '/FinanceService/GetHistory',
                request_serializer=finance__pb2.HistoryRequest.SerializeToString,
                response_deserializer=finance__pb2.HistoryResponse.FromString,
                _registered_method=True)


class FinanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Fitur ke-3 & Streaming: Server-side streaming untuk mendapatkan history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTransaction,
                    request_deserializer=finance__pb2.TransactionRequest.FromString,
                    response_serializer=finance__pb2.TransactionResponse.SerializeToString,
            ),
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=finance__pb2.SummaryRequest.FromString,
                    response_serializer=finance__pb2.SummaryResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=finance__pb2.HistoryRequest.FromString,
                    response_serializer=finance__pb2.HistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FinanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FinanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinanceService/AddTransaction',
            finance__pb2.TransactionRequest.SerializeToString,
            finance__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FinanceService/GetSummary',
            finance__pb2.SummaryRequest.SerializeToString,
            finance__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/FinanceService/GetHistory',
            finance__pb2.HistoryRequest.SerializeToString,
            finance__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
