# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'finance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfinance.proto\"U\n\x12TransactionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\"&\n\x13TransactionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eSummaryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"O\n\x0fSummaryResponse\x12\x14\n\x0ctotal_income\x18\x01 \x01(\x01\x12\x15\n\rtotal_expense\x18\x02 \x01(\x01\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x01\"!\n\x0eHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"A\n\x0fHistoryResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t2\xb1\x01\n\x0e\x46inanceService\x12;\n\x0e\x41\x64\x64Transaction\x12\x13.TransactionRequest\x1a\x14.TransactionResponse\x12/\n\nGetSummary\x12\x0f.SummaryRequest\x1a\x10.SummaryResponse\x12\x31\n\nGetHistory\x12\x0f.HistoryRequest\x1a\x10.HistoryResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=17
  _globals['_TRANSACTIONREQUEST']._serialized_end=102
  _globals['_TRANSACTIONRESPONSE']._serialized_start=104
  _globals['_TRANSACTIONRESPONSE']._serialized_end=142
  _globals['_SUMMARYREQUEST']._serialized_start=144
  _globals['_SUMMARYREQUEST']._serialized_end=177
  _globals['_SUMMARYRESPONSE']._serialized_start=179
  _globals['_SUMMARYRESPONSE']._serialized_end=258
  _globals['_HISTORYREQUEST']._serialized_start=260
  _globals['_HISTORYREQUEST']._serialized_end=293
  _globals['_HISTORYRESPONSE']._serialized_start=295
  _globals['_HISTORYRESPONSE']._serialized_end=360
  _globals['_FINANCESERVICE']._serialized_start=363
  _globals['_FINANCESERVICE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
